In [1]:
import pandas as pd

In [ ]:
espires = pd.read_csv('../data/espires_bici.csv')
espires.head()

/var/folders/vs/5hqqq9px6_z7w4dnv2j4238m0000gn/T/ipykernel_17264/1832672302.py:1: DtypeWarning: Columns (0,1,3,9,10,11,12,13,14,16,18,19,20,21,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  espires = pd.read_csv('data/espires_bici.csv')

,Geo Point,Geo Shape,angulo,fecha_actualizacion,hora_actualizacion,idpm,ih,datetime,Àngul / Ángulo,Data Actualització / Fecha Actualización,...,hora_actua,created_us,created_da,last_edite,last_edi_1,gid,created_user,created_date,last_edited_user,last_edited_date
0,"39.4534281344,-0.371417928","{""coordinates"": [-0.371417928, 39.4534281344],...",30.0,NaN,NaN,2255.0,0.0,2023-07-31 00:00:05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"39.4701858226,-0.3434149115","{""coordinates"": [-0.3434149115, 39.4701858226]...",251.0,NaN,NaN,1822.0,0.0,2023-07-31 00:00:05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"39.4823568143,-0.3910134347","{""coordinates"": [-0.3910134347, 39.4823568143]...",184.0,NaN,NaN,1043.0,0.0,2023-07-31 00:00:05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"39.4795695506,-0.3610574679","{""coordinates"": [-0.3610574679, 39.4795695506]...",70.0,NaN,NaN,1439.0,0.0,2023-07-31 00:00:05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"39.4617384023,-0.3591412053","{""coordinates"": [-0.3591412053, 39.4617384023]...",166.0,NaN,NaN,435.0,0.0,2023-07-31 00:00:05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
espires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10059654 entries, 0 to 10059653
Data columns (total 27 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Geo Point                                 object
 1   Geo Shape                                 object
 2   angulo                                    float64
 3   fecha_actualizacion                       object
 4   hora_actualizacion                        float64
 5   idpm                                      float64
 6   ih                                        float64
 7   datetime                                  object
 8   Àngul / Ángulo                            float64
 9   Data Actualització / Fecha Actualización  object
 10  Hora Actualització / Hora Actualización   object
 11  fiwareid                                  object
 12  geo_shape                                 object
 13  geo_point_2d                              object
 14  globalid                                  object
 15  OBJECTID                                  float64
 16  fecha_actu                                object
 17  hora_actua                                float64
 18  created_us                                object
 19  created_da                                object
 20  last_edite                                object
 21  last_edi_1                                object
 22  gid                                       float64
 23  created_user                              object
 24  created_date                              object
 25  last_edited_user                          object
 26  last_edited_date                          object
dtypes: float64(8), object(19)
memory usage: 2.0+ GB

In [4]:
espires.describe()

,angulo,hora_actualizacion,idpm,ih,Àngul / Ángulo,OBJECTID,hora_actua,gid
count,3.319200e+06,7.468200e+05,9.786154e+06,4.408615e+06,3.730320e+06,15930.000000,0.0,135.000000
mean,1.610667e+02,2.022101e+13,1.855971e+03,4.997494e+01,1.659481e+02,203.000000,NaN,203.000000
std,6.815531e+01,2.343752e-02,1.197105e+03,1.114869e+02,6.661658e+01,38.971297,NaN,39.115214
min,3.000000e+01,2.022101e+13,0.000000e+00,-1.000000e+00,3.000000e+01,136.000000,NaN,136.000000
25%,1.177500e+02,2.022101e+13,1.043000e+03,0.000000e+00,1.210000e+02,169.000000,NaN,169.500000
50%,1.610000e+02,2.022101e+13,1.544000e+03,0.000000e+00,1.620000e+02,203.000000,NaN,203.000000
75%,2.100000e+02,2.022101e+13,2.628000e+03,6.000000e+01,2.130000e+02,237.000000,NaN,236.500000
max,3.260000e+02,2.022101e+13,5.006000e+03,9.628000e+03,3.260000e+02,270.000000,NaN,270.000000

In [6]:
espires.count()

Geo Point                                    3319200
Geo Shape                                    3319200
angulo                                       3319200
fecha_actualizacion                           750357
hora_actualizacion                            746820
idpm                                         9786154
ih                                           4408615
datetime                                    10059654
Àngul / Ángulo                               3730320
Data Actualització / Fecha Actualización     1082692
Hora Actualització / Hora Actualización       719280
fiwareid                                      284566
geo_shape                                    6466954
geo_point_2d                                 6466954
globalid                                       33615
OBJECTID                                       15930
fecha_actu                                      3186
hora_actua                                         0
created_us                                     15930
created_da                                     15930
last_edite                                     15930
last_edi_1                                     15930
gid                                              135
created_user                                     135
created_date                                     135
last_edited_user                                 135
last_edited_date                                 135
dtype: int64

In [ ]:
e = pd.read_csv('espires_bici01-01-2023_00-00-02.csv', sep=';')
e.head()

,Geo Point,Geo Shape,angulo,fecha_actualizacion,hora_actualizacion,idpm,ih
0,"39.4761065759,-0.3930172919","{""coordinates"": [-0.3930172919, 39.4761065759]...",120,NaN,NaN,835,0
1,"39.4830214772,-0.3795902989","{""coordinates"": [-0.3795902989, 39.4830214772]...",177,NaN,NaN,1165,0
2,"39.4875811893,-0.3883149929","{""coordinates"": [-0.3883149929, 39.4875811893]...",131,NaN,NaN,1045,0
3,"39.4772727258,-0.3679871844","{""coordinates"": [-0.3679871844, 39.4772727258]...",184,NaN,NaN,1441,0
4,"39.4929344573,-0.3832858719","{""coordinates"": [-0.3832858719, 39.4929344573]...",288,NaN,NaN,4025,0